# Lightweight Python environment
FROM python:3.10-slim

WORKDIR /app

# Dependencies installation
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Streamlit frontend app file copy karte hain
COPY app.py .

EXPOSE 8501

# Streamlit config set karte hain taake docker environment network par crash na kare
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]